ci: bulid and test rustup and cargo is executable

diff --git a/.github/workflows/test.yaml b/.github/workflows/test.yaml
--- a/.github/workflows/test.yaml
+++ b/.github/workflows/test.yaml
@@ -111,28 +111,30 @@ jobs:
     - uses: docker/setup-buildx-action@d70bba72b1f3fd22344832f00baa16ece964efeb # v3.3.0
       with:
         driver-opts: network=host
-    - uses: docker/build-push-action@2cdde995de11925a030ce8070c3d77a52ffcf1c0 # v5.3.0
-      if: ${{ startsWith(matrix.otp, '24') }}
-      with:
-        platforms: linux/${{ matrix.arch }}
-        cache-from: type=local,src=/tmp/.docker-buildx-cache,mode=max
-        build-args: |
-          BUILD_FROM=${{ steps.base_tag.outputs.image }}
-          OTP_VERSION=${{ matrix.otp }}
-          ELIXIR_VERSION=${{ matrix.elixir }}
-          BUILD_WITHOUT_QUIC=1
-          EMQTT_BENCH_VERSION=0.4.5
-          LUX_VERSION=lux-2.6
-        file: ./Dockerfile
-        context: .
-    - uses: docker/build-push-action@2cdde995de11925a030ce8070c3d77a52ffcf1c0 # v5.3.0
-      if: ${{ ! startsWith(matrix.otp, '24') }}
+    - name: Build and load docker image
+      uses: docker/build-push-action@2cdde995de11925a030ce8070c3d77a52ffcf1c0 # v5.3.0
       with:
         platforms: "linux/${{ matrix.arch }}"
+        load: true # Load the image to the runner's docker daemon
+        tags: test-image:latest
         cache-from: type=local,src=/tmp/.docker-buildx-cache,mode=max
         build-args: |
           BUILD_FROM=${{ steps.base_tag.outputs.image }}
           OTP_VERSION=${{ matrix.otp }}
           ELIXIR_VERSION=${{ matrix.elixir }}
+          BUILD_WITHOUT_QUIC=${{ startsWith(matrix.otp, '24') && 1 || '' }}
+          EMQTT_BENCH_VERSION=${{ startsWith(matrix.otp, '24') && '0.4.5' || '' }}
+          LUX_VERSION=${{ startsWith(matrix.otp, '24') && 'lux-2.6' || '' }}
         file: ./Dockerfile
         context: .
+    - name: Test OTP 27 Image (Rust should exist)
+      if: startsWith(matrix.otp, '27')
+      run: |
+        docker run --rm test-image:latest bash -c "rustup --version && cargo --version"
+    - name: Test non-OTP 27 Image (Rust should NOT exist)
+      if: "!startsWith(matrix.otp, '27')"
+      run: |
+        if docker run --rm test-image:latest bash -c "command -v rustup"; then
+          echo "Error: rustup was found in an image where it should not be."
+          exit 1
+        fi
